### ISSUE TITLE
"Infinite" durability armor takes damage/breaks, not infinite

### ISSUE THREAD

**Issue by skysurveil** [DivineRPG/DivineRPG#397]
**DivineRPG version**
1.6.4.1

**Describe the bug**
All "Infinite" durability armor pieces take damage and break once they reach durability 0.

**To reproduce**
Both **Elite Realmite Armor** and **Arlemite Armor** set pieces acquire a durability bar upon damage and break when 0 is reached.

**Expected behavior**
I expected the infinite durability armor pieces to not have traditional durability bars or at least not break when they reach 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/46916978/90365667-fdcc0800-e01a-11ea-874f-d542bd1b3556.png)

**Additional context**
N/A

**Comment by NicosaurusRex99** [comment]
Notice, it doesnt say infinite durability in the full set perks
we nerfed armor

**Comment by skysurveil** [comment]
> Notice, it doesnt say infinite durability in the full set perks
> we nerfed armor

Thank you for clarifying. I wish the wiki would mention that change because originally infinite durability armor sets are still listed as infinite. As a result, I cannot know what kind of durability any of the originally infinite sets have until crafting them and taking damage.

Is there anywhere to easily view the durability values for all armor sets since the wiki is outdated?

**Comment by NicosaurusRex99** [comment]
press f3 + h and then type in JEI the name of that armor piece.
also the wiki is unofficial and outdated

**Comment by skysurveil** [comment]
> press f3 + h and then type in JEI the name of that armor piece.
> also the wiki is unofficial and outdated

Advanced tooltips were already enabled, I've been able to see durability (uses) for weapons but durability is not visible for any armor sets, that's why I was asking if there was another way to view all armor durability values.
![image](https://user-images.githubusercontent.com/46916978/90368445-e131cf00-e01e-11ea-844b-c8826e57ec66.png)

**Comment by NicosaurusRex99** [comment]
![image](https://user-images.githubusercontent.com/11579935/90368636-85605800-e0a9-11ea-816d-0996869693b6.png)


Short of hovering over each item no there isnt

**Comment by skysurveil** [comment]
![image](https://user-images.githubusercontent.com/46916978/90368780-7765f500-e01f-11ea-8a6f-bdebf4367a96.png)
![image](https://user-images.githubusercontent.com/46916978/90369071-f22f1000-e01f-11ea-9d9d-4905d6e888bf.png)
![image](https://user-images.githubusercontent.com/46916978/90369271-5356e380-e020-11ea-9381-59e4acaca964.png)


Whether looking in JEI or the same item within the inventory it does not list durability for me unless it's already taken damage.

I'm trying to figure out if there's an additional setting I don't have enabled that's not showing me that specific info.

**Comment by NicosaurusRex99** [comment]
I dont know what it would be but for me i just pushed f3 + h and it shows

**Comment by skysurveil** [comment]
> I dont know what it would be but for me i just pushed f3 + h and it shows

JEI version 4.15.0.296? I'm only behind by one version, I don't know how it could show me everything but the durability info in the pop up unless it's already taken damage.

Which JEI version are you running?

**Comment by NicosaurusRex99** [comment]
I think that its actually a forge thing
Forge: 14.23.5.2847
JEI: 4.15.0.296

**Comment by skysurveil** [comment]
> I think that its actually a forge thing
> Forge: 14.23.5.2847
> JEI: 4.15.0.296

Forge: 14.23.5.2854
JEI: same version.

I will try installing a separate forge profile with that older version and see if that fixes it.

**Comment by skysurveil** [comment]
![image](https://user-images.githubusercontent.com/46916978/90371225-7c2ca800-e023-11ea-8723-c37bcba518f5.png)
Running that forge version did not fix it.

You don't have cheat mode set to true, do you? I can't imagine I would have to give myself admin privileges on my server to simply see the durability info.

**Comment by NicosaurusRex99** [comment]
i play singleplayer. check in single player

**Comment by skysurveil** [comment]
![image](https://user-images.githubusercontent.com/46916978/90371687-2a385200-e024-11ea-9495-26517402ce18.png)
Same result in singeplayer world.
(Still testing on your 2847 forge version)
Enabling JEI cheat mode in singleplayer also did not fix it.

**Comment by NicosaurusRex99** [comment]
@Tslat any ideas?

**Comment by Tslat** [comment]
Durability isn't normally shown until damage is done to the item

**Comment by skysurveil** [comment]
> Durability isn't normally shown until damage is done to the item

**Normally?** So is it possible for me to somehow view the durability info in the JEI overview like in the picture @NicosaurusRex99 provided above?

I just want some way to view the durability of armor sets without having to make the armor and then take damage to find out what sort of durability it actually has.

The only workaround I can think of is going into creative and giving myself every piece of armor and taking damage wearing every single one, then compiling a list of the durability for every one. But that seems way too involved for the simple problem I'm trying to solve. Somehow @NicosaurusRex99 is able to view all of the armor durability without having it in their inventory and/or taking damage, I just want to have the same functionality.

[ArmorDurability.txt](https://github.com/DivineRPG/DivineRPG/files/5086974/ArmorDurability.txt)
Here is a compiled list of all armor durability values in case anyone else cannot see armor durability without it being damaged.
